### PR TITLE
Guestbook - Staging Implementation

### PR DESCRIPTION
**Pull request by codyhoag**
Hey @matethurzo,

@peerkar and I have finalized the Staging implementation for the documentation team's Guestbook application. I will begin writing the learning path documentation based on this code to describe step-by-step instructions for adding Staging and Export/Import to a modular app.

Can you review the code for best practices?

FYI, this PR is meant for the `liferay-docs` repo's `7.0.x` branch, but your profile does not have it, so I sent to your `master` branch instead.

### CODE REVIEW

**Comment by akosthurzo** [comment]
Hi @codyhoag ,

I have reviewed this pull and it looks great overall. There are only a few things to mention:
1. In the StagedModelDataHandlers' doImportMissingReference we usually do a null check to avoid NPE later:
```
 if (existingEntry == null) {
	return;
}
```

2. GuestbookPortletDataHandler.doDeleteData(): Why does the PDH handle the deletion of the entries? I think this logic should be in the local service.

3. I think it is better to separate the code you modified from the generated code. For example I usually commit the changes in service.xml separately and I only have one commit for service builder generated files on the top of the changes.

Please note that I did not modify the code because it does not follow the source formatting rules (the whole code base, not the staging parts specifically) and I don't know if you would like to change that or not.

Thanks,
Akos

/cc @matethurzo

**Comment by codyhoag** [comment]
Hey @akosthurzo; thanks for reviewing:
1. Thanks for recommending this; I've added this to both SMDHs' `doImportMissingReference` methods.
2. I'm seeing mixed usages for this in our official Liferay apps. For example, I looked up three examples of PDHs used in our source:
    - Blogs has the PDH in the `*-web` module.
    - Journal and Bookmarks have the PDH in the `*-service` module.
    - All three apps have the `doDeleteData()` method living in the PDH.
    Are there reasons for this being different among apps? How should we proceed in our case?
3. Good point; I separated the `service.xml` modification from the generated part the first time, but the second time I made a modification, I lumped them together. I'll make sure this is obvious in the docs.

For source formatting, our team did not apply them when this app was started. I'd like to apply the SF plugin and run it so we follow best practices, but it isn't a huge concern since our docs will be providing all the snippets (which will be SF'd correctly). Nevertheless, I'll see if we can apply some SF rules once Staging is merged.

**Comment by peerkar** [comment]
2) Agree definitely. The deletion should definitely happen inside the transactional border, in the service. Will you @codyhoag  do the changes or would you like me to do those?

Code formatting: I used the Eclipse formatter found [here](https://web.liferay.com/community/wiki/-/wiki/Main/Development+Style). Is that not the right one?

**Comment by matethurzo** [comment]
@peerkar @codyhoag 
2) it does not really matter where you put it, but we generally recommend the service or impl bundles. Mostly because these codes are offering services to the framework and not related to the web pieces in any way.

the transation boundary is a good point but the staging framework itself takes care of that, everything in a data handler is happening within the same transaction.

**Comment by codyhoag** [comment]
@matethurzo thanks for the info

@peerkar if you don't mind, It'd be great if you could move the deletion code to the appropriate place 😊 . I hope this is the last request I ask of you! Thanks for bearing through this with me!

**Comment by codyhoag** [comment]
Thanks guys. I have the code all updated and just tested. Everything is looking great! Once the 7.1 topics die down some, I plan on documenting the entire Staging implementation process using the Guestbook app as an example. Thanks again!

**Pull request closed without merging**
